# Default settings loaded by main.py:cli_main if no custom settings are provided.

# --- Global settings ---
gl_version = [4, 1]
fps = 60
presentation_delay = 4

# --- Arduino settings ---
[arduino]
# port = "/dev/ttyUSB0"
port = "dummy"
baud_rate = 9600
trigger_command = "T"


[paths]
# Override if you want to work from non-default directory for stimuli etc.
data_dir = ""
log_dir = ""

# --- Window definitions ---
[windows.default]
# Window size should be exactly as it appears in the OS's display manager.
# For example, if a 1080p monitor is in portrait mode, it should have a (W,H)
# shape of (1080, 1920). 
window_size = [500, 500] # (W,H)
# How to transform the stimuli to match the window.
#  - mirror horizontally, then
#  - rotate (by degrees)
# mirror and rotate are passed to a StimProgram which (optionally) uses them.
mirror = false
rotation = 0
fullscreen = false
style = "transparent"
# The channels of the stimulus from which each RGB display channel draws from.
# This could be [0, 0, 0] to have all outpus be equal to the (possibly only)
# first channel.
channels = [0, 1, 2]
# Color to display when stimulus is not playing.
# RGB values will be interpreted as sRGB by the monitor. 
clear_rgba = [0.73, 0.73, 0.73, 1.0]

[windows."1"]
# -- shift is an offset from (0,0) at bottom left. 
x_shift = -1080
y_shift = 1000

# Don't add a second window, as custom configs could not be able to 
# specify just a single window, as the _deep_merge would add this second
# window.
# [windows."2"]
# x_shift = -500
# y_shift = 1000
# mirror = false
# rotation = 0
# window_size = [500, 500]
# fullscreen = false
# style = "transparent"
# channels = [0, 1, 2]
# # RGB values will be interpreted as sRGB by the monitor. 
# clear_rgba = [0.73, 0.73, 0.73, 1.0]
